sudo SetFile -m "12/02/2022 06:50:18" Install\ macOS\ Ventura.app/
sudo SetFile -m "12/02/2022 06:50:18" Install\ macOS\ Ventura.app/Contents/SharedSupport
sudo SetFile -d "12/02/2022 06:50:18" Install\ macOS\ Ventura.app/Contents/SharedSupport
sudo SetFile -m "12/02/2022 06:50:18" Install\ macOS\ Ventura.app/Contents/SharedSupport/SharedSupport.dmg
sudo SetFile -d "12/02/2022 06:50:18" Install\ macOS\ Ventura.app/Contents/SharedSupport/SharedSupport.dmg
sudo SetFile -m "12/02/2022 06:50:19" Install\ macOS\ Ventura.app/Contents
sudo SetFile -m "12/02/2022 06:50:18" Install\ macOS\ Ventura.app/Contents/Frameworks
sudo SetFile -m "12/02/2022 06:50:19" Install\ macOS\ Ventura.app/Contents/Frameworks/OSInstallerSetup.framework
sudo SetFile -m "12/02/2022 06:50:19" Install\ macOS\ Ventura.app/Contents/Frameworks/OSInstallerSetup.framework/Versions
sudo SetFile -m "12/02/2022 06:50:18" Install\ macOS\ Ventura.app/Contents/Frameworks/OSInstallerSetup.framework/Versions/A/Frameworks/OSInstallerSetupInternal.framework
sudo SetFile -m "12/02/2022 06:50:18" Install\ macOS\ Ventura.app/Contents/Frameworks/OSInstallerSetup.framework/Versions/A/Frameworks/OSInstallerSetupInternal.framework/Versions
sudo SetFile -m "12/02/2022 06:50:18" Install\ macOS\ Ventura.app/Contents/Frameworks/OSInstallerSetup.framework/Versions/A/Frameworks/IAESD.framework
sudo SetFile -m "12/02/2022 06:50:18" Install\ macOS\ Ventura.app/Contents/Frameworks/OSInstallerSetup.framework/Versions/A/Frameworks/IAESD.framework/Versions
sudo SetFile -m "12/02/2022 06:50:18" Install\ macOS\ Ventura.app/Contents/Frameworks/OSInstallerSetup.framework/Versions/A/Frameworks/IAESD.framework/Versions/A/Frameworks/IAOSPersonalization.framework
sudo SetFile -m "12/02/2022 06:50:18" Install\ macOS\ Ventura.app/Contents/Frameworks/OSInstallerSetup.framework/Versions/A/Frameworks/IAESD.framework/Versions/A/Frameworks/IAOSPersonalization.framework/Versions
sudo SetFile -m "12/02/2022 06:50:18" Install\ macOS\ Ventura.app/Contents/Frameworks/OSInstallerSetup.framework/Versions/A/Frameworks/IAESD.framework/Versions/A/Frameworks/IABridgeOSInstall.framework
sudo SetFile -m "12/02/2022 06:50:18" Install\ macOS\ Ventura.app/Contents/Frameworks/OSInstallerSetup.framework/Versions/A/Frameworks/IAESD.framework/Versions/A/Frameworks/IABridgeOSInstall.framework/Versions
sudo SetFile -m "12/02/2022 06:50:18" Install\ macOS\ Ventura.app/Contents/Frameworks/OSInstallerSetup.framework/Versions/A/Frameworks/IAESD.framework/Versions/A/Frameworks/IAMiniSoftwareUpdate.framework
sudo SetFile -m "12/02/2022 06:50:18" Install\ macOS\ Ventura.app/Contents/Frameworks/OSInstallerSetup.framework/Versions/A/Frameworks/IAESD.framework/Versions/A/Frameworks/IAMiniSoftwareUpdate.framework/Versions
sudo SetFile -m "12/02/2022 06:50:18" Install\ macOS\ Ventura.app/Contents/Frameworks/OSInstallerSetup.framework/Versions/A/Frameworks/IAESD.framework/Versions/A/Frameworks/IAPackageKit.framework
sudo SetFile -m "12/02/2022 06:50:18" Install\ macOS\ Ventura.app/Contents/Frameworks/OSInstallerSetup.framework/Versions/A/Frameworks/IAESD.framework/Versions/A/Frameworks/IAPackageKit.framework/Versions
sudo SetFile -m "12/02/2022 06:50:18" Install\ macOS\ Ventura.app/Contents/Frameworks/OSInstallerSetup.framework/Versions/A/Frameworks/IAESD.framework/Versions/A/Frameworks/IAInstallerUtilities.framework
sudo SetFile -m "12/02/2022 06:50:18" Install\ macOS\ Ventura.app/Contents/Frameworks/OSInstallerSetup.framework/Versions/A/Frameworks/IAESD.framework/Versions/A/Frameworks/IAInstallerUtilities.framework/Versions